Homework1
Anatoliy24/loft-taxi pull request #1
Opened 2020-11-20 13:11 UTC by Anatoliy24

2020-11-20 14:54 UTC, KustovAA requested changes

2020-11-20 14:54 UTC, KustovAA commented on .idea/.gitignore
> +# Default ignored files
добавь .idea в  файл .gitignore

2020-11-20 14:54 UTC, KustovAA commented on package.json
> +    "loft-taxi-mui-theme": "^1.2.0",
убери неиспользуемые зависимости

2020-11-20 14:54 UTC, KustovAA commented on src/App.js
> +    const [page, setPage] = React.useState('login');
используй useState без React

2020-11-20 14:54 UTC, KustovAA commented on src/App.js
> +                <div>
Сделай объект pages где ключ название страницы, а значение компонент. Что-то вроде:
```
const pages = {
    login: <Login onSubmit={(pageName) => setPage(pageName)}/>,
    main: <Main/>
}
```

И в коде просто
```
<StylesProvider injectFirst>
    {pages[page]}
</StylesProvider>
```

2020-11-20 14:54 UTC, KustovAA commented on src/components/authForm.js
> +                                type={'password'}
почему в фигурных скобках строка?

2020-11-20 14:54 UTC, KustovAA commented on src/components/header.js
> +                <path fillRule="evenodd" clipRule="evenodd" d="M30.5 61C47.3447 61 61 47.3447 61 30.5C61 26.9626 60.3978 23.5658 59.2903 20.4066L20.4066 59.2903C23.5658 60.3978 26.9626 61 30.5 61ZM5.
вынеси svg в компонент `Logo` прям в этом файле и вставь сюда компонентом

2020-11-20 14:54 UTC, KustovAA commented on src/components/registrationForm.js
> +                            type={'password'}
почему в фигурных скобках строка?

2020-11-20 14:54 UTC, KustovAA commented on src/components/selectForm.js
> +    const [open, setOpen] = React.useState(false);
просто импорт useState отдельной функцией без React

2020-11-20 14:54 UTC, KustovAA commented on src/pages/profile.js
> +
убери пустое место

2020-11-20 14:54 UTC, KustovAA commented on src/pages/login.js
> +                    <path d="M128.792 163.16L127.136 169.136H103.16L106.976 163.16H128.792ZM119.468 171.548L115.112 187.964H106.868L111.332 171.548H119.468ZM150.984 169.208H135.432L140.616 163.16H149
вынеси svg в компонент

2020-11-20 14:54 UTC, KustovAA commented on src/pages/profile.js
> +    // const classes = useStyles();
убери закоменченный код тут и в остальных местах

2020-11-20 17:08 UTC, Anatoliy24 commented on src/App.js
> +    const [page, setPage] = React.useState('login');
+

2020-11-20 17:09 UTC, Anatoliy24 commented on src/components/authForm.js
> +                                type={'password'}
готово

2020-11-20 17:09 UTC, Anatoliy24 commented on src/components/registrationForm.js
> +                            type={'password'}
готово

2020-11-20 17:09 UTC, Anatoliy24 commented on src/components/selectForm.js
> +    const [open, setOpen] = React.useState(false);
готово

2020-11-20 17:09 UTC, Anatoliy24 commented on src/pages/profile.js
> +
готово

2020-11-20 17:10 UTC, Anatoliy24 commented on src/pages/login.js
> +                    <path d="M128.792 163.16L127.136 169.136H103.16L106.976 163.16H128.792ZM119.468 171.548L115.112 187.964H106.868L111.332 171.548H119.468ZM150.984 169.208H135.432L140.616 163.16H149
готово

2020-11-20 17:10 UTC, Anatoliy24 commented on src/pages/profile.js
> +    // const classes = useStyles();
готово

2020-11-21 14:51 UTC, Anatoliy24 commented on src/App.js
> +                <div>
готово

2020-11-22 19:32 UTC, KustovAA requested changes

2020-11-22 19:32 UTC, KustovAA commented on src/App.js
> +    const [page, setPage] = React.useState('login');
Все еще вижу `React.useState`, а не `useState`

2020-11-22 19:32 UTC, KustovAA commented on src/App.js
>                  ?
На твое усмотрение

можно 
```
{page !== 'login' && (
    <div>
        {header}
    </div>
)}
```
кажется, что так лучше выглядит

2020-11-22 19:32 UTC, KustovAA commented on src/App.js
> +        main:<Main/>,
пробел после `:`

2020-11-22 19:32 UTC, KustovAA commented on src/pages/login.js
>                  {authForm == 'loginForm'
сделай как тут https://github.com/Anatoliy24/loft-taxi/pull/1/commits/c5304d1f6e2c10969462c948328c0908d39e9a5d#diff-3d74dddefb6e35fbffe3c76ec0712d5c416352d9449e2fcc8210a9dee57dff67R14

2020-11-23 06:31 UTC, Anatoliy24 commented on src/App.js
> +        main:<Main/>,
готово

2020-11-23 06:37 UTC, Anatoliy24 commented on src/App.js
> +    const [page, setPage] = React.useState('login');
готово

2020-11-23 06:45 UTC, Anatoliy24 commented on src/App.js
>                  ?
готово

2020-11-23 07:04 UTC, Anatoliy24 commented on src/pages/login.js
>                  {authForm == 'loginForm'
готово

2020-11-23 09:24 UTC, KustovAA approved these changes

2020-11-23 09:24 UTC, merged