homework-2 map, propsType, useContext
Anatoliy24/loft-taxi pull request #2
Opened 2020-11-26 08:20 UTC by Anatoliy24

2020-11-29 11:38 UTC, KustovAA requested changes

2020-11-29 11:38 UTC, KustovAA commented on src/App.js
> +
убери пустую линию

2020-11-29 11:38 UTC, KustovAA commented on src/App.js
> +    const onSubmitLogout = () => {
добавь пустую линию между функциями

2020-11-29 11:38 UTC, KustovAA commented on src/components/authForm.js
> +
слишком большой отступ между `AuthForm.propTypes` и `AuthForm `

2020-11-29 11:38 UTC, KustovAA commented on src/styles/style.scss
> +  //width: 100%;
убери эти стили совсем, раз ты уже подключил карту

2020-11-29 11:38 UTC, KustovAA commented on src/App.js
> +            setIsLoggedIn(true);
у тебя обрабатывается случай верного пароля, выведи подсказку о том, что пароль неверный

2020-11-29 18:52 UTC, Anatoliy24 commented on src/App.js
> +            setIsLoggedIn(true);
+

2020-11-29 18:53 UTC, Anatoliy24 commented on src/App.js
> +
готово

2020-11-29 18:54 UTC, Anatoliy24 commented on src/App.js
> +    const onSubmitLogout = () => {
готово

2020-11-29 18:54 UTC, Anatoliy24 commented on src/components/authForm.js
> +
готово

2020-11-29 18:55 UTC, Anatoliy24 commented on src/styles/style.scss
> +  //width: 100%;
готово

2020-12-01 15:43 UTC, KustovAA approved these changes

2020-12-01 15:43 UTC, merged