homework-3-1
Anatoliy24/loft-taxi pull request #3
Opened 2020-12-07 19:58 UTC by Anatoliy24

Сделано все, кроме тестов для редьюсеров

2020-12-09 09:39 UTC, KustovAA requested changes

2020-12-09 09:39 UTC, KustovAA commented on src/App.js
> +let PrivateRouter = ({
const вместо let
и вынеси PrivateRouter в отдельный компонент

2020-12-09 18:55 UTC, KustovAA requested changes

2020-12-09 18:55 UTC, KustovAA commented on src/App.js
> +    console.log(isLoggedIn)
убери консоль лог

2020-12-09 18:55 UTC, KustovAA commented on src/App.js
> +                <PrivateRouter
2 одинаковых роута

2020-12-09 18:55 UTC, KustovAA commented on src/index.js
> +import {PersistGate} from 'redux-persist/integration/react'
Убери совсем персист отовсюду

2020-12-09 18:55 UTC, KustovAA commented on src/components/header.js
> +
сделай на логаут localStorage.removeItem для всех полей информации о пользователе

2020-12-09 19:11 UTC, Anatoliy24 commented on src/App.js
> +let PrivateRouter = ({
готово

2020-12-09 19:11 UTC, Anatoliy24 commented on src/App.js
> +    console.log(isLoggedIn)
готово

2020-12-09 19:12 UTC, Anatoliy24 commented on src/App.js
> +                <PrivateRouter
готово

2020-12-09 19:15 UTC, Anatoliy24 commented on src/index.js
> +import {PersistGate} from 'redux-persist/integration/react'
готово

2020-12-10 07:33 UTC, KustovAA approved these changes

2020-12-10 14:54 UTC, merged