Homework4
Anatoliy24/loft-taxi pull request #4
Opened 2020-12-16 14:12 UTC by Anatoliy24

2020-12-16 19:54 UTC, KustovAA requested changes

2020-12-16 19:54 UTC, KustovAA commented on src/actions/routeAction.js
> +
сделай между всеми блоками отступ в 1 строку

2020-12-16 19:54 UTC, KustovAA commented on src/api.js
> +export const registration = async (dataReg) =>{
подними на верх и отступ в 1 строку между функциями

2020-12-16 19:54 UTC, KustovAA commented on src/api.js
> +export const registration = async (dataReg) =>{
и в остальных файлах также

2020-12-16 19:54 UTC, KustovAA commented on src/components/map.js
> +    console.log('mapContainerRef', mapContainerRef)
убери консоль логи

2020-12-16 19:54 UTC, KustovAA commented on src/components/selectForm.js
> +
отступы в одну строку между блоками кода

2020-12-16 19:54 UTC, KustovAA commented on src/components/selectForm.js
> +                                <MenuItem value={addressFrom} key={index}>{addressFrom}</MenuItem>
```
{addressListArray.filter((addressFrom) => addressFrom !== addressTo).map((addressFrom, index) => (
    <MenuItem value={addressFrom} key={index}>{addressFrom}</MenuItem>
))}
```
Сделай такой форматирование

2020-12-16 19:54 UTC, KustovAA commented on src/components/selectForm.js
> +                                <MenuItem value={addressTo} key={index}>{addressTo}</MenuItem>
и тут отформатируй, как я показал выше

2020-12-16 19:54 UTC, KustovAA commented on src/pages/Main.js
> +            {(profileData.nameUser) && (profileData.numberCard) && (profileData.expiryDate) && (profileData.cvc)
вынеси это в переменную
`const isSelect = profileData.nameUser && profileData.numberCard && profileData.expiryDate && profileData.cvc`

2020-12-16 19:54 UTC, KustovAA commented on src/sagas/addressListSaga.js
> +    }catch (error){
пробел между } и catch

2020-12-16 19:54 UTC, KustovAA commented on src/sagas/addressListSaga.js
> +    }catch (error){
и везде так

2020-12-17 16:04 UTC, Anatoliy24 commented on src/api.js
> +export const registration = async (dataReg) =>{
готово

2020-12-17 16:04 UTC, Anatoliy24 commented on src/components/map.js
> +    console.log('mapContainerRef', mapContainerRef)
готово

2020-12-17 16:05 UTC, Anatoliy24 commented on src/components/selectForm.js
> +
готово

2020-12-17 16:06 UTC, Anatoliy24 commented on src/components/selectForm.js
> +                                <MenuItem value={addressFrom} key={index}>{addressFrom}</MenuItem>
готово

2020-12-17 16:06 UTC, Anatoliy24 commented on src/components/selectForm.js
> +                                <MenuItem value={addressTo} key={index}>{addressTo}</MenuItem>
готово

2020-12-17 16:09 UTC, Anatoliy24 commented on src/pages/Main.js
> +            {(profileData.nameUser) && (profileData.numberCard) && (profileData.expiryDate) && (profileData.cvc)
готово

2020-12-17 16:09 UTC, Anatoliy24 commented on src/sagas/addressListSaga.js
> +    }catch (error){
готово

2020-12-21 04:43 UTC, merged